htmx_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/urls.py
from django.urls import path
from .views import *

app_name = "tasks" 

urlpatterns = [
    path('', Task.as_view(), name='post_task'),
    path('get_tasks/', get_tasks, name='get_tasks'),
]

tasks/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Todo(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

tasks/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from .models import *
from django.contrib import messages


class Task(View):
    template_name = 'tasks/post_task.html'

    def get(self, request):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})

    def post(self, request):
        title = request.POST.get('title')
        id_category = int(request.POST.get('category'))
        try:
            category = Category.objects.get(id=id_category)
            Todo.objects.create(title=title, category=category)
        except Category.DoesNotExist :
            messages.error(request, "Echec d'enregistrement")
        except Exception as e:
            messages.error(request, "Une erreur s'est produit dans le système")
        return redirect('tasks:post_task')

def get_tasks(request):
    tasks = Todo.objects.all()
    return render(request, 'components/get_task.html', {'tasks': tasks})

templates/components/get_task.html
{% load static %}
{% for item in tasks %}
<div class="container d-flex justify-content-between shadow-sm mb-4">
    <div class="container">
        <p class='bg-primary p-2 d-inline rounded text-bg-primary mb-3 badge-p'>{{item.category}}</p>
        <p class='mt-3 fw-semibold'>Evènement : {{item.title}}</p>
    </div>
</div>
{% endfor %}

templates/index.html
{% load static %}
<html lang="">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Django Htmx</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400..800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <script src="{% static 'js/bootstrap.bundle.min.js' %}" defer></script>
  <script src="{% static 'js/htmx.min.js' %}" defer></script>
</head>

<body>
  <div></div>
  {% block index %}

  {% endblock %}
</body>

</html>

templates/tasks/post_task.html
{% extends "index.html" %}
{% load static %}
{% block index %}
<div>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'tasks:post_task' %}">Django htmx</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
    </div>
  </nav>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      {% if messages %}
      {% for message in messages %}
      <div class=" mt-4 alert {{message.tags}} text-center mt-3">{{message}}</div>
      {% endfor %}
      {% endif %}
      <form hx-post="{% url 'tasks:post_task' %}" hx-swap="outerHTML" hx-target="body">
        {% csrf_token %}
        <div class="mb-3">
          <label for="title" class='form-label'>Evènement</label>
          <input type="text" class='form-control' name='title'>
        </div>
        <div class="mb-3">
          <label for="category" class='form-label'>Category</label>
          <select name="category" id="category" class='form-select'>
            {% for item in categories %}
            <option value="{{item.id}}">{{item.name}}</option>
            {% endfor %}
          </select>
        </div>
        <button type='submit' class='btn btn-primary'>Enregistrer</button>
      </form>
    </div>
    <div class="col-md-5" hx-get="{% url 'tasks:get_tasks' %}" hx-trigger="load" hx-target="this"></div>
  </div>
</div>
{% endblock index %}